### PR TITLE
Updated odbc driver version to 17.5.2.1 from 17.4.2.1

### PR DESCRIPTION
**Pull request by sutarsha**

### CODE REVIEW

**Comment by Roemer** [comment]
Thank you for you change. Unfortunatley I coudln't replace the package on chocolatey yet. I'm trying to figure out how to do that.

**Comment by sutarsha** [comment]
Thank you for your reply. When do you think you'll be in a position to update/replace the package?
This is a blocker for me right now. 

Many Thanks!!

**Comment by Roemer** [comment]
I published a new package version: 15.0.1300.359001 Give it a try.

**Comment by sutarsha** [comment]
Thank you. It is working now. I really appreciate your quick response.

**Pull request merged**
